services:
  app:
    volumes:
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
      - storage_data:/var/www/html/storage
